language: python
python:
- '3.6'
install:
- pip install --progress-bar off torch==1.2.0+cpu torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
- pip install --progress-bar off .
script:
- cd tests && sh run_tests.sh
